version: '3'

services:
  findcm-next-app:
    container_name: findcm-next-app
    command: pnpm run prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    volumes:
      - ./:/app
      - ./public:/app/public
      - /app/node_modules
      - /app/.next
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  nginx:
    image: nginx:1.22-alpine
    container_name: nginx
    volumes:
      - ./:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443

networks:
  my_network:
    external: true